baseURL = "https://mogeko.me" # <head> 里面的 baseurl 信息，填你的博客地址
title = "Mogeko`s Blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题 (需要自己下载)

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt


preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[params]
    since = 2017
    author = "Mogeko"                          # Author's name
    avatar = "/blog-images/r/me/avatar.jpg"           # Author's avatar
    subtitle = "Just for Fun"                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统

    google_verification = ""

    description = "Mogeko 的个人博客" # (Meta) 描述
    keywords = "blog, KMS, Hugo, GNU/Linux, Linux, Ubuntu, Rusty Lake: Roots, Hollow Knight, 空洞骑士" # site keywords

    beian = ""
    baiduAnalytics = ""
    googleAnalytics = "UA-104502658-2" # Google 统计 id

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    # GitHub = "Mogeko"
    # Twitter = "xxoo"
    # Email   = "zhengjunyi@live.com"
    # Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Facebook = "xxoo"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

[markup.goldmark.renderer]
    unsafe = true

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "936cecdd2ab935870ca5" # Your client ID
    clientSecret = "39cfc7a3cb9a974b6609f3fdaa637e2917e3e40a" # Your client secret
    repo = "blog-commits" # The repo to store comments
    owner = "Mogeko" # Your GitHub ID
    admin= "Mogeko" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
